# Droits d'auteur des contributeurs kubeinit
# Tous les droits sont réservés.
#
# Licence sous la licence Apache, version 2.0 (la "Licence"); tu peux
# Ne pas utiliser ce fichier sauf en conformité avec la Licence. Vous pouvez obtenir
# une copie de la licence à

#  http://www.apache.org/licenses/LICENSE-2.0

# Sauf si requis par la loi applicable ou convenu par écrit, le logiciel
# distribué sous licence est distribué sur une BASE "TEL QUEL", SANS
# GARANTIES OU CONDITIONS DE QUELQUE NATURE QUE CE SOIT, expresses ou implicites. Voir le
# Licence pour la langue spécifique régissant les autorisations et les limitations
# sous la licence.

# Toutes les variables destinées à être modifiées doivent être placées dans ce fichier.

# Toutes les variables de ce rôle doivent avoir un préfixe de "kubeinit_okd_"

kubeinit_okd_debug: "{{ (ansible_verbosity | int) >= 2 | bool }}"
kubeinit_okd_hide_sensitive_logs: true

kubeinit_okd_pod_cidr: 10.100.0.0/14
kubeinit_okd_service_cidr: 172.30.0.0/16

kubeinit_okd_wait_for_cluster_to_converge: True

kubeinit_okd_network_type: "OpenShiftSDN"

kubeinit_okd_openshift_deploy: "{{ hostvars['kubeinit-env'].openshift_deploy }}"

kubeinit_okd_registry: quay.io
kubeinit_okd_registry_organization_aux: "{% if ( kubeinit_okd_openshift_deploy | default(False) ) %}
                                             openshift-release-dev
                                         {% else %}
                                             openshift
                                         {% endif %}"
kubeinit_okd_registry_organization: "{{ kubeinit_okd_registry_organization_aux | replace(' ','') }}"

kubeinit_okd_registry_repository_aux: "{% if ( kubeinit_okd_openshift_deploy | default(False) ) %}
                                           ocp-release
                                       {% else %}
                                           okd
                                       {% endif %}"
kubeinit_okd_registry_repository: "{{ kubeinit_okd_registry_repository_aux | replace(' ','') }}"

kubeinit_okd_registry_release_tag_aux: "{% if ( kubeinit_okd_openshift_deploy | default(False) ) %}
                                              4.7.18
                                        {% else %}
                                              4.9.0-0.okd-2022-01-29-035536
                                        {% endif %}"
kubeinit_okd_registry_release_tag: "{{ kubeinit_okd_registry_release_tag_aux | replace(' ','') }}"

kubeinit_okd_registry_release_tag_major: "{{ kubeinit_okd_registry_release_tag.split('.')[0] }}"
kubeinit_okd_registry_release_tag_minor: "{{ kubeinit_okd_registry_release_tag.split('.')[1] }}"
kubeinit_okd_registry_release_tag_rev: "{{ kubeinit_okd_registry_release_tag.split('.')[2] }}"

kubeinit_okd_registry_release_url_aux: "{% if ( kubeinit_okd_openshift_deploy | default(False) ) %}
                                           https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ kubeinit_okd_registry_release_tag }}/release.txt
                                       {% else %}
                                           https://api.github.com/repos/openshift/okd/releases/tags/{{ kubeinit_okd_registry_release_tag }}
                                       {% endif %}"
kubeinit_okd_registry_release_url: "{{ kubeinit_okd_registry_release_url_aux | replace(' ','') }}"

kubeinit_okd_registry_pullsecret: '  { "auths": {} }'
kubeinit_okd_registry_pullsecret_empty: '  { "auths": {} }'

kubeinit_okd_dependencies_client_aux: "{% if ( kubeinit_okd_openshift_deploy | default(False) ) %}
                                          https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ kubeinit_okd_registry_release_tag }}/openshift-client-linux-{{ kubeinit_okd_registry_release_tag }}.tar.gz
                                       {% else %}
                                          https://github.com/openshift/okd/releases/download/{{ kubeinit_okd_registry_release_tag }}/openshift-client-linux-{{ kubeinit_okd_registry_release_tag }}.tar.gz
                                       {% endif %}"

kubeinit_okd_dependencies_installer_aux: "{% if ( kubeinit_okd_openshift_deploy | default(False) ) %}
                                              https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ kubeinit_okd_registry_release_tag }}/openshift-install-linux-{{ kubeinit_okd_registry_release_tag }}.tar.gz
                                          {% else %}
                                              https://github.com/openshift/okd/releases/download/{{ kubeinit_okd_registry_release_tag }}/openshift-install-linux-{{ kubeinit_okd_registry_release_tag }}.tar.gz
                                          {% endif %}"

kubeinit_okd_dependencies:
  client: "{{ kubeinit_okd_dependencies_client_aux | replace(' ','') }}"
  installer: "{{ kubeinit_okd_dependencies_installer_aux | replace(' ','') }}"

kubeinit_okd_fcos_stream: "stable"
kubeinit_okd_fcos_release: "34.20210626.3.1"
# kubeinit_okd_rhcos_release: "4.8.2"
# kubeinit_okd_rhcos_release_major_minor: "{{ kubeinit_okd_rhcos_release.split('.')[0] }}.{{ kubeinit_okd_rhcos_release.split('.')[1] }}"

kubeinit_okd_coreos_images:
  fcos:
    uri: "https://builds.coreos.fedoraproject.org/prod/streams/{{ kubeinit_okd_fcos_stream }}/builds/{{ kubeinit_okd_fcos_release }}/x86_64/"
    kernel: "fedora-coreos-{{ kubeinit_okd_fcos_release }}-live-kernel-x86_64"
    initrd: "fedora-coreos-{{ kubeinit_okd_fcos_release }}-live-initramfs.x86_64.img"
    raw: "fedora-coreos-{{ kubeinit_okd_fcos_release }}-metal.x86_64.raw.xz"
    sig: "fedora-coreos-{{ kubeinit_okd_fcos_release }}-metal.x86_64.raw.xz.sig"
    rootfs: "fedora-coreos-{{ kubeinit_okd_fcos_release }}-live-rootfs.x86_64.img"
